services:
  beshop:
    image: ${DOCKER_REGISTRY-}beshop
    build:
      context: .
      dockerfile: BEShop/Dockerfile
    depends_on:
      - database
  database:
    image: postgres:15
    container_name: DATABASE
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=EShop
     - POSTGRES_HOST_AUTH_METHOD=trust
     - PGDATA=/data/pgdata
    ports:
     - "5432:5432"
