#services:
#  beshop:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=5000
#      - OPENAI_API_KEY=sk-Yq4XDCkGpotqlIyRAesbGw
#      - OPENAI_BASE_URL=https://kurim.ithope.eu/v1
#    ports:
#      - "5000"
#
