services:
  beshop:
    image: ${DOCKER_REGISTRY-}beshop
    build:
      context: .
      dockerfile: BEShop/Dockerfile
    depends_on:
      - postgresbase
  postgresbase:
    image: postgres:latest
    environment:
     - POSTGRES_DB=EShop
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - POSTGRES_HOST_AUTH_METHOD=trust
     # - PGDATA=/data/pgdata
    ports:
     - 4020:5432
