services:
  beshop:
    image: ${DOCKER_REGISTRY-}beshop
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    build:
      context: .
      dockerfile: BEShop/Dockerfile
    ports:
      - "5000"
    depends_on:
      - postgresbase
  postgresbase:
    image: postgres:15
    environment:
     - POSTGRES_DB=EShop
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - POSTGRES_HOST_AUTH_METHOD=trust
     # - PGDATA=/data/pgdata
    ports:
     - 4020:5432
